name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: "RunatRate Managment.sln"          
      Wap_Project_Directory: "RunatRateManagment.Package"
      Wap_Project_Path: RunatRateManagment.Package\RunatRateManagment.Package.wapproj
      DOTNET_ROOT: C:\Program Files\dotnet
      PFX_PASSWORD: "Demo123!"  # Password used when exporting the self-signed certificate

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore solution
      run: dotnet restore "$env:Solution_Name"

    # Build the solution
    - name: Build solution
      run: dotnet build "$env:Solution_Name" --configuration ${{ matrix.configuration }} --no-restore

    # Run unit tests
    - name: Run unit tests
      run: dotnet test "$env:Solution_Name" --configuration ${{ matrix.configuration }} --no-build

    # Copy self-signed PFX certificate from repo to WAP project folder
    - name: Copy signing certificate
      run: |
        $pfx_source = "./certs/SigningCertificate.pfx"
        $pfx_dest = Join-Path -Path $env:Wap_Project_Directory -ChildPath "GitHubActionsWorkflow.pfx"

        if (!(Test-Path $env:Wap_Project_Directory)) {
            New-Item -ItemType Directory -Path $env:Wap_Project_Directory | Out-Null
        }

        Copy-Item -Path $pfx_source -Destination $pfx_dest

    # Build and package the WAP project
    - name: Create app package
      run: msbuild "$env:Wap_Project_Path" `
            /p:Configuration=${{ matrix.configuration }} `
            /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode `
            /p:AppxBundle=$env:Appx_Bundle `
            /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx `
            /p:PackageCertificatePassword=$env:PFX_PASSWORD
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload

    # Remove the temporary PFX file
    - name: Remove signing certificate
      run: Remove-Item -Path "$env:Wap_Project_Directory\GitHubActionsWorkflow.pfx"

    # Upload the MSIX package
    - name: Upload MSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
